server:
  port: 8888
spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArsenOOO7/timetable-configuration
          clone-on-start: true
          default-label: master
        native:
          search-locations: classpath:/config