server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/arsen/Projects/Repos/Java/timetable-micro/timetable-config-service/src/main/resources/config

