version: "3.8"

services:
  postgres:
    image: "postgres:16.2"
    container_name: "timetable-postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: "elasticsearch:8.12.2"
    container_name: "timetable-elasticsearch"
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - timetable-esdata:/usr/share/timetable-elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 3GB
        reservations:
          memory: 1GB

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "timetable-rabbitmq"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  timetable-esdata:
    driver: local