spring:
  cloud:
    function:
      definition: updateGroupEvent;updateTimetableEvent
    stream:
      bindings:
        updateGroupEvent-in-0:
          destination: group-topic
          group: group-update-queue
        updateTimetableEvent-in-0:
          destination: lesson-topic
          group: lesson-update-queue