server:
  port: 8080
jwt:
  token:
    header: Timetable-Authentication
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://identity-access
          predicates:
            - Path=/api/auth/**

        - id: users
          uri: lb://identity-access
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: classrooms
          uri: lb://classrooms
          predicates:
            - Path=/api/classroom/**
          filters:
            - AuthenticationFilter

        - id: group-management
          uri: lb://group-management
          predicates:
            - Path=/api/group/management/**

        - id: groups
          uri: lb://groups
          predicates:
            - Path=/api/group/**

        - id: subjects
          uri: lb://subjects
          predicates:
            - Path=/api/subject/**

        - id: teachers
          uri: lb://teachers
          predicates:
            - Path=/api/teacher/**

        - id: timetable
          uri: lb://timetable
          predicates:
            - Path=/api/timetable/**

management:
  endpoint:
    gateway:
      enabled: true
