server:
  port: 7003
spring:
  profiles:
    active: ${TIMETABLE_ACTIVE_PROFILE:local}
  application:
    name: timetable-group-ms
  config:
    import: configserver:${configUrl:http://localhost:7777}
