server:
  port: 8004

spring:
  cloud:
    function:
      definition: teacherUpdateEventConsumer;classroomUpdateEventConsumer;subjectUpdateEventConsumer
    stream:
      bindings:
        teacherUpdateEventConsumer-in-0:
          destination: teacher-topic
          group: teacher-up-to-date
        classroomUpdateEventConsumer-in-0:
          destination: classroom-topic
          group: classroom-up-to-date
        subjectUpdateEventConsumer-in-0:
          destination: subject-topic
          group: subject-up-to-date

resilience4j:
  circuitbreaker:
    instances:
      group-management-service:
        failureRateThreshold: 30
        slow-call-duration-threshold: 10000ms