server:
  port: 7777

spring:
  application:
    name: timetable-config-ms
  profiles:
    active: local, native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArsenOOO7/timetable-configuration
          clone-on-start: true
          basedir: timetable-config/target/config